### ISSUE TITLE
프로필 이미지 칩 구현

### ISSUE THREAD

**Issue by gw-lim** [Peachy-Peachy/Taskify#39]

**Comment by kde98892** [comment]
이거 왜 close 이상하게 되어있죠?

**Comment by gw-lim** [comment]
> 이거 왜 close 이상하게 되어있죠?

제가 중복으로 이슈를 만들어서 삭제하려고 했는데 이슈는 삭제가 안되더라구요... 이런 방식으로 close 밖에 안돼요
